version: '3.8'
services:
  dev-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    networks:
      - freecodecamp
  test-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5435:5432"
    networks:
      - freecodecamp
networks:
  freecodecamp: